### ISSUE TITLE
Tmux Learn how to run the command

### ISSUE THREAD

**Issue by connschi** [CharlesStockman/linuxConfiguration#18]
I have my configuration in a file which includes information about number of windows per terminal, there locations and properties.

The command which are executed are:

> * `cd linuxConfiguration/distrofiles/tmux`
> * `tmux`
> * `tmux source-file ./.tmux.config`

Best outcome would be to execute one tmux command from anywhere the directory hierarchy.

**Comment by CharlesStockman** [comment]
Fixed by creating the following command :  tmux -s SessionName "tmux source-file <filename such as ./tmux.conf>"

**Comment by CharlesStockman** [comment]
The correct command has been found : tmux -s SessionName "tmux source-file <filename such as ./tmux.conf>"
